name: Run R Script and Commit Results

on:
  schedule:
    - cron: '5 14 * * *'
  workflow_dispatch:  # Allows manual triggering from GitHub Actions tab

jobs:
  run_r_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        install.packages("tidyRSS")
        install.packages("tidyverse")
        install.packages("lubridate")

    - name: Run the R script
      run: Rscript scripts/fetch_data.R  # Make sure the path is correct

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Commit and Push if changes exist
      run: |
        git add -A
        git commit -m "Updated data files from scheduled R script" || echo "No changes to commit"
        git push
